### PR TITLE
Google Colab Updates

### PR DESCRIPTION
**Pull request by PrashantDixit0**
This PR adds 
1. Updated Colab with proper instructions and comments to make it easy to understand. 
2. Colab opens directly from GitHub rather than from Google Drive.
3. Added Open with Colab button.
4. Added images in `data/detect` for not downloading images for inferencing

### CODE REVIEW

**Comment by PrashantDixit0** [comment]
@wondervictor @StevenGrove

**Comment by wondervictor** [comment]
Hi @PrashantDixit0, I've reviewed this PR and it's a good improvement, thank you very much!

**Comment by PrashantDixit0** [comment]
I'll start working on adding other features in YOLO-World :+1:

**Comment by wondervictor** [comment]
I'm looking forward to it ✌️!

**Pull request merged**
